using System.Text.Json.Serialization;

namespace SUS.EOS.NeoWallet.Services.Models;

/// <summary>
/// Wallet type classification
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum WalletType
{
    Key, // Standard private key
    Ledger, // Hardware wallet
    Imported, // Imported from external source
    Generated, // Generated by this wallet
}
